---
- name: Post-Install - Get Kubernetes Version for Weave
  shell: >
    kubectl version | base64 | tr -d '\n'
  register: weave_k8s_version
  run_once: true


- name: Post-Install - Install Weave
  command: >
    kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version={{ weave_k8s_version.stdout }}"
  register: weave
  changed_when: "'created' in weave.stdout"
  run_once: true
