---
- name: Worker - Check if worker is into a cluster
  stat:
    path: "/etc/kubernetes/kubelet.conf"
  register: worker


- name: Worker - Join
  command: >
    {{ join_command.stdout_lines[0] }}
    {{ kubernetes_worker_join_command_extra_opts }}
  when:
    - not worker.stat.exists


- name: Worker - Iptables Rule
  command: >
    iptables -t nat -I KUBE-SERVICES -d 10.96.0.1/32 -p tcp -m comment --comment "default/kubernetes:https cluster IP" -m tcp --dport 443 -j KUBE-MARK-MASQ
  when:
    - not worker.stat.exists


- name: Worker - Label
  command: kubectl label node {{ ansible_hostname }} --overwrite node-role.kubernetes.io/worker=
  delegate_to: "{{ groups.masters | first }}"
  register: label
  retries: 5
  delay: 12
  until: label.rc == 0
