---
# Kubernetes properties
kubernetes_version: 1.19.8


# Cluster properties
kubernetes_cluster_control_plane_endpoint: ""
kubernetes_cluster_apiserver_ip: ""
kubernetes_cluster_apiserver_port: 6443
kubernetes_cluster_init_extra_opts: ""

# Master
kubernetes_master_iface: eth1
kubernetes_master_join_command_extra_opts: ""

# Worker
kubernetes_worker_join_command_extra_opts: ""
